import "./auth.css";



export const metadata = {
    title: "Auth",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body
          
        >
            <h1>MY AUTH </h1>
          {children}
        </body>
      </html>
    );
  }
  